/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// OptionsTokenItem struct for OptionsTokenItem
type OptionsTokenItem struct {
	Remark string `json:"remark,omitempty"`
	Token  string `json:"token,omitempty"`
}
