/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ApiGroupContent struct for AppApiV1GroupGroupIdContentGet
type ApiGroupContent struct {
	TrxId        string `json:"TrxId,omitempty"`
	Data         string `json:"Data,omitempty"`
	GroupId      string `json:"GroupId,omitempty"`
	ResendCount  int64  `json:"ResendCount,omitempty"`
	SenderPubkey string `json:"SenderPubkey,omitempty"`
	TimeStamp    string `json:"TimeStamp,omitempty"`
	Version      string `json:"Version,omitempty"`
}
