/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ApiNSdkAnnounceParams struct for ApiNSdkAnnounceParams
type ApiNSdkAnnounceParams struct {
	Data PbAnnounceItem `json:"data"`
}
